[common]
model = ./faster-whisper-large-v3-turbo
lang = ja
device = cuda
compute = float16

[advanced]
; 高级参数，可根据需要调整，未设置时使用默认值
gap_penalty = -10
similarity_offset = 50
default_duration = 5.0
max_combine = 20
beam_size = 5
vad_filter = False
vad_parameters = {}